//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.trips = new HashSet<trip>();
        }
    
        public int contract_id { get; set; }
        public int client_id { get; set; }
        public int contract_material_id { get; set; }
        public Nullable<decimal> client_contract_rate { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<decimal> contract_partner_rate { get; set; }
        public int location_from { get; set; }
        public int location_to { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_to { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual client client { get; set; }
        public virtual contractLocation contractLocation { get; set; }
        public virtual contractLocation contractLocation1 { get; set; }
        public virtual contractMaterial contractMaterial { get; set; }
        public virtual partner partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip> trips { get; set; }
    }
}
