//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportCorp_DBEntities : DbContext
    {
        public TransportCorp_DBEntities()
            : base("name=TransportCorp_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<app_error_log> app_error_log { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<contractLocation> contractLocations { get; set; }
        public virtual DbSet<contractMaterial> contractMaterials { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<financer> financers { get; set; }
        public virtual DbSet<ownership_type> ownership_type { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<trip> trips { get; set; }
        public virtual DbSet<tripType> tripTypes { get; set; }
        public virtual DbSet<usrpasrecord> usrpasrecords { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
        public virtual DbSet<vehicleOwnership> vehicleOwnerships { get; set; }
    }
}
