//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public int trip_id { get; set; }
        public int vehicle_id { get; set; }
        public System.DateTime trip_date { get; set; }
        public int trip_type_id { get; set; }
        public int client_id { get; set; }
        public int contract_id { get; set; }
        public Nullable<int> financer_id { get; set; }
        public Nullable<decimal> contract_partner_rate { get; set; }
        public decimal material_weight { get; set; }
        public int trip_driver_id { get; set; }
        public Nullable<decimal> diesel_exp { get; set; }
        public Nullable<decimal> rokad { get; set; }
        public Nullable<decimal> bitti { get; set; }
        public Nullable<decimal> other_exp { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual client client { get; set; }
        public virtual contract contract { get; set; }
        public virtual driver driver { get; set; }
        public virtual financer financer { get; set; }
        public virtual tripType tripType { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
