//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.trips = new HashSet<trip>();
        }
    
        public int vehicle_id { get; set; }
        public string rego_no { get; set; }
        public Nullable<int> ownership_type_id { get; set; }
        public string vehicle_type { get; set; }
        public Nullable<int> manufacturing_year { get; set; }
        public string chassis_no { get; set; }
        public string engine_no { get; set; }
        public int vehicle_owner_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual ownership_type ownership_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip> trips { get; set; }
        public virtual vehicleOwnership vehicleOwnership { get; set; }
    }
}
